app/components/Grid.js, app/containers/Vote.jsx, app/containers/data.js
Updated Grid to be a functional component,
Added data for viewing.
=> Grid component

app/components/Cell.jsx, app/components/Grid.js, app/components/Headers.jsx, app/containers/Vote.jsx, app/css/components/table.css
=> Table stlye

app/actions/sheet.js, app/components/Sheet/Cell.jsx, app/components/Sheet/Grid.js, app/constants/index.js, app/css/components/table.css, app/reducers/sheet.js, package.json
Lots on unfinished update cell redux stuff
=> content editable and modals

app/actions/sheet.js, app/components/Sheet/AddRow.jsx, app/components/Sheet/Cell.jsx, app/components/Sheet/Grid.js, app/components/Sheet/RowModal.jsx, app/components/Sheet/Table.jsx, app/constants/index.js, app/css/components/table.css, app/css/main.css, app/reducers/sheet.js, app/reducers/sheetState.js
We can add rows now. 
Cells expand when editing and mulitple lines; looks ok could use some ui help
Row modals now load the correct row info
=> major spreadsheet updates

app/actions/sheet.js, app/components/Sheet/AddColumn.jsx, app/components/Sheet/ColumnOptions.jsx, app/components/Sheet/Headers.jsx, app/constants/index.js, app/reducers/sheet.js
We have to decide on how we are going to add new IDs to columns. Other than that, this is good.
=> Add column

app/actions/SpaceControls.js, app/reducers/spacecontrol.js, server/controllers/workspaces.js
quick fix based on refactoring
closes #58
=> new sheet tab now using sheetId

app/actions/sheet.js, app/components/Sheet/Cell.jsx, app/components/Sheet/ModalTypes/ImageList.jsx, app/components/Sheet/ModalTypes/Text.jsx, app/components/Sheet/ModalTypes/filepicker.jsx, app/components/Sheet/RowModal.jsx, app/components/Sheet/Table.jsx, app/constants/index.js, app/containers/SpaceControl.jsx, app/css/components/modal.css, app/css/components/table.css, app/css/main.css, app/reducers/sheet.js, app/reducers/sheetState.js, app/routes.jsx, app/server.jsx, package.json
Modal now only updates the grid when you close out of it.
=> Modal Updates working for "text" type cells

app/actions/sheet.js, app/components/Sheet/ColumnOptions.jsx, app/components/Sheet/Grid.jsx, app/components/Sheet/Table.jsx, app/constants/index.js, app/reducers/sheet.js
=> Column menu

seed.js
=> Seed update

app/components/Sheet/MenuEditCol.jsx, app/reducers/sheet.js
Users can input custom function in function type columns.
=> Custom func

app/actions/sheet.js, app/components/Sheet/Cell.jsx, app/components/Sheet/Grid.jsx, app/components/Sheet/Table.jsx, app/components/SpaceControls/SearchButton.jsx, app/components/SpaceControls/SuperBar.jsx, app/constants/index.js, app/containers/SpaceControl.jsx, app/css/components/magic-bar.css, app/css/components/table.css, app/reducers/sheet.js
closes #110 
Allows user to edit cells while search is happening. when search bar reclicked it will show the full grid again.
Approach used: css class is added to row based on the search term if it should be hidden
=> Search bar tuning

app/components/Sheet/ColumnOptions.jsx
=> removed delete option form first column

app/reducers/sheet.js
update that allows the magic bar to be magic again
=> small fix for magic bar based on new current cell focus check

app/components/BottomBar/BottomReducers.jsx, app/components/Sheet/ColumnOptions.jsx, app/css/components/table.css
adds glyphs to column headers for types and median for the bottom bar
=> Column styling

app/components/Sheet/Headers.jsx, app/server.jsx
=> console logs removed in headers

app/actions/sheet.js, app/components/BottomBar/BottomReducers.jsx
=> map markers filtered

app/components/SpaceControls/SuperBar.jsx, app/containers/SpaceControl.jsx
Enter from Magic Bar working
closes #187
=> Cell styles

app/components/SpaceControls/SuperBar.jsx, app/css/components/magic-bar.css
=> Super bar ce

app/actions/SpaceControls.js
=> searching off on sheet change

app/reducers/sheet.js
sets the current cell to null on any deletion
=> removes current cell on delete

app/tests/reducers/FormulaStore-test.js
Tests all action types in formulaStore reducer
=> Formula tests
